packets/auth.go, packets/connack.go, packets/disconnect.go, packets/puback.go, packets/pubcomp.go, packets/publish.go, packets/pubrec.go, packets/pubrel.go, packets/suback.go, packets/unsuback.go, paho/client.go, paho/client_test.go, paho/server_test.go
=> Don't add 0 byte buffers to net.Buffers

packets/properties.go, paho/cp_connack.go
=> Add SessionExpiryInterval to CONNACK

paho/client.go
=> Fix client.Incoming() recv PINGRESP

paho/client.go
closes #43 
Maybe this is not elegant
=> add paho Client OnClientError()

paho/client.go, paho/message_ids.go, paho/message_ids_test.go
Also improve performance of getting a new mid and add tests
resolves #46
=> Ensure that MIDs are freed after use

packets/packets.go, paho/client.go, paho/cp_utils.go, paho/router.go
Got the test back to front for error codes on PUBREL so weren't sending
PUBCOMP responses.
Also weren't handling user properties correctly
resolves #49
=> Correct handling of PUBREL

paho/client.go
=> Always release semaphore in publish function

paho/client.go
=> Ensure that go routines finish on disconnect/error

README.md, autopaho/examples/queue/main.go, autopaho/examples/queue/subscribe.go, autopaho/readme.md, paho/session/state/ids_test.go, paho/session/state/sendquota.go, paho/session/state/sendquota_test.go, paho/session/state/state.go, paho/store/memory/store.go
Minor fixes to examples and documentation
=> Minor fixes to examples and documentation

paho/session/state/state.go
This was not really necessary so best to support 1.20.
closes #177
=>  Go 1.20 compatibility - Remove context.AfterFunc

paho/router.go, paho/router_test.go
Adds a default Handler to StandardRouter which would simplify removing SingleHandlerRouter.
This is also useful to have (I generally use it to log any unexpected messages as it means
there is probably a bug!).
ref #168
=> Add defaultHandler to standard router

paho/client.go
paho would panic if keepalive was 0.
=> Accept 0 keepalive

autopaho/queue_test.go
=> fix queue_test (missed one instance of memory.)

paho/cp_publish.go
Also don't panic if String is called on nil `paho.Publish`
closes #87
closes #162
=> duplicate flag now gettable in `paho.Publish`

paho/client.go, paho/client_test.go, paho/cmd/rpc/main.go
This demonstrated how Router could be replaced in a mostly non-breaking way.
Note that I have not worked through all examples to test (know that autopaho/rpc will be broken).
reference #168
=> Replace Router with OnPublishReceived Callback

paho/store/file/store.go
=> Sync when writing to file store

paho/extensions/rpc/rpc.go
paho RPC Request did not honor context
closes #108
=> Prevent RPC blocking when context cancelled

autopaho/auto.go, autopaho/auto_test.go, autopaho/net.go
This PR implements the changes as discussed in issue #268.
=> Allow ConnectPacketBuilder to fail

paho/extensions/topicaliases/topicliases.go, paho/extensions/topicaliases/topicliases_test.go
=> Fix the topic disappear when registering a new topic alias in the TAHandler

internal/basictestserver/server.go
Resolves a data race in the test server (impact on tests only)
=> Potential data race in TestServer

Makefile
**Do not create a Pull Request without creating an issue first**
#295
*The design of your solution to the problem should be discussed and agreed in an issue before submitting the PR*
It  is a simple typo issue
**ECA - Eclipse Contributer Agreement**
yes
Please provide enough information so that others can review your pull request:
There will no error after errors
**Testing**
root@localhost:/data/paho.golang# make build
go build -o ./bin/chat ./paho/cmd/chat
go build -o ./bin/rpc ./paho/cmd/rpc
go build -o ./bin/stdinpub ./paho/cmd/stdinpub
go build -o ./bin/stdoutsub ./paho/cmd/stdoutsub
go build -o ./bin/rpc_auto ./autopaho/examples/rpc
go: downloading github.com/gorilla/websocket v1.5.3
go: downloading golang.org/x/net v0.35.0
=> build_rpc_cm: update Makefile path issue

autopaho/examples/docker/binds/mosquitto/config/mosquitto.conf, autopaho/examples/docker/docker-compose.yml, autopaho/examples/docker/readme.md
Fix ` docker-compose.yml` to run properly and update `readme.md` to current configuration/setup.
=> fix autopaho Docker example
