paho/client.go
paho/client_test.go

The call to the OnDisconnect handler was scheduled before the disconnect
process had completed, because the user may legitimately want to call
Connect() again in this handler don't call it until disconnected.

Fix tests and don't call OnDisconnect early

---

packets/packets.go
paho/client.go
paho/client_test.go
paho/cmd/chat/main.go
paho/cmd/rpc/main.go
paho/cmd/stdoutsub/main.go
paho/pinger.go
paho/server_test.go

As reported in #19 the cleanup function in Connect will attempt to Stop
the PingHandler, as it happens the PingHandler will not have been
started at any point before when cleanup() may be called. However
Incoming() will have been started and will also attempt to Stop()
PingHandler which in the issue given will still have a nil channel
Also I've added some more error checks.

Check the ping channel is not nil in Stop()

---

paho/client.go
paho/cmd/chat/main.go
paho/cp_publish.go
paho/extensions/rpc/rpc.go
paho/extensions/topicaliases/topicliases.go
paho/extensions/topicaliases/topicliases_test.go

Added a publishHook function to clientconfig that if set is called
before the publish is sent, this function can modify the Publish and is
used in the extension to do automatic topic aliasing
#29

Add extension to provide automatic topic aliasing

---

go.mod
go.sum
packets/connect.go
packets/packets.go
packets/packets_test.go
packets/properties.go
paho/cmd/chat/main.go
paho/cp_auth.go
paho/cp_connack.go
paho/cp_connect.go
paho/cp_disconnect.go
paho/cp_publish.go
paho/cp_pubresp.go
paho/cp_suback.go
paho/cp_subscribe.go
paho/cp_unsuback.go
paho/cp_unsubscribe.go
paho/cp_utils.go
paho/pinger.go

It was pointed out that the key for user properties can be used
multiple times so a map was not the right solution, changed
to a slice of struct instead and modified the packet structs
fixes #21

Make user properties a slice of struct not map

---

paho/pinger.go

Signed-off-by: a-wing <1@233.email>
- Fix `lastPing` always is `0001-01-01 00:00:00 +0000 UTC`
- Fix  `atomic pingOutstanding` always is `0`
I think it is more reasonable to print the log after WriteTo conn

Fix pinger lastPing && atomic

---

packets/properties.go
paho/cp_publish.go
paho/cp_subscribe.go

Mistakenly had the sub id down as a uint32 rather than the variable
byte integer that the spec says, tbh I think the uint32 would have been
a better choice, vbis suck
closes #39

SubscriptionIdentifier should be a VBI

---

go.mod
go.sum
packets/properties_test.go
paho/client.go
paho/client_test.go
paho/cp_publish.go
paho/message_ids_test.go
paho/router.go
paho/server_test.go

Sorry for not creating an issue first but I developed this for the company I work for so I'm creating a draft PR to test the waters. I think it may be more useful to discuss this with the code changes at hand. If it doesn't work for you I can still open an issue first, please let me know.
This PR aims to solve two issues:
1. Message ordering: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901240
2. Message acknowledgment only after the message processing has completed to ensure re-delivery of "unacked" messages from the server in case of abnormal client termination
In order to avoid blocking the `Incoming()` loop (which would lead to unexpected behaviours such as client disconnections etc...) you are routing the `PUBLISH` packets asynchronously (i.e. by creating a …

In-order routing and late ack

---

Makefile
paho/client.go
paho/client_test.go
paho/message_ids_test.go

This PR is to address the deadlock on cleanups, see [here](https://github.com/eclipse/paho.golang/issues/54).
It also addresses another bug that I found related to canceled contexts. It was causing panics due to the usual nil pointer dereference (e.g. `cap *packets.Connack` was passed as `nil` [here](https://github.com/eclipse/paho.golang/blob/6f81099163c2cbbe7862b98e28062baca74cd275/paho/client.go#L244) causing the `panic`).
* wait for `CONNACK` without starting `incoming` worker
* this helped with the removal of the deadlock
* handle all context errors
* move all workers at the end of `Connect` when all operations have completed successfully
* making `incoming` and `error` methods unexported
* this helped me restrict the context where the lock could be acquired by the user calling a …

Deadlock + minor bugfixes

---

paho/client.go
paho/client_test.go

I noticed the panic while I had the manual acknowledgments branch running in our production systems.
I'm proposing the bugfix here so that I can rebase my other branch and remove the bugfix from there, since it's not related to the [manual acknowledgments](https://github.com/eclipse/paho.golang/pull/57).
As usual I wrote the test first to make sure that I was able to replicate the `panic`. The test replicated the `panic` successfully at least once every three executions. Then I made the changes and ran the test in a loop for at least ~1k times. The `panic` does not occur anymore nor I was able to find deadlocks.
These changes are now live in production along with the manual acks changes. So far we haven't noticed anything unusual.

panic: send on closed channel

---

autopaho/auto.go
autopaho/examples/docker/binds/mosquitto/config/mosquitto.conf
autopaho/examples/docker/docker-compose.yml
autopaho/examples/docker/readme.md
autopaho/net.go
go.mod
go.sum

Add support for websocket connections to AutoPaho. The docker example has been updated to make use of this.
Ref Issue: #61

Add websocket support to AutoPaho

---

packets/publish.go
paho/acks_tracker.go
paho/acks_tracker_test.go
paho/client.go
paho/client_test.go

This PR is to address this issue: https://github.com/eclipse/paho.golang/issues/53
We want the ability to manually control the PUBACK/PUBREC transmission in order to avoid message loss.
The idea is to acknowledge a message only after it has been processed successfully by a client.
* the default behaviour is not changed, acks will be sent in order automatically by the client, right after routing
* if the users want to manually enable acknowledgments they just have to set `EnableManualAcknowledgment` to `true` and then call `Ack()` in any order. the client will take care of sending the acks to the server back in right order.
* this is something I've seen implemented in other MQTT clients (e.g. HiveMQ Java client)
* a background routine will periodically try to flush the acks in order, by …

Manual acknowledgments

---

Makefile
autopaho/auto.go
autopaho/auto_test.go
autopaho/net.go

Closes #68 allowing configuration of Connect packet parameters in autopaho.
Slight variations on the proposed interface, but should be essentially the same. 
As this is my first PR on Paho repos, I'm happy to iterate with any feedback provided.
**Testing**
As the autopaho module did not previously have dedicated tests, I have implemented a unittest only for the ClientConfig construction, and related validation of the Connect packet my changes introduced.
I'm also using my fork in an implementation, and it's demonstrably working, correctly authenticating with a broker, etc. 🙂

autopaho: set connect packet parameters

---

autopaho/net.go
packets/packets.go
packets/packets_test.go
paho/client.go

This PR fixes race conditions when writing to net.Conn that doesn't implement
net.writeBuffers, such as tls.Conn.
There is an example reproduction of the race condition (and the fix) in `authopaho/examples/docker` at https://github.com/thejan2009/paho.golang/commits/packets-writeto
Closes #81

Introduce AtomicWriteTo(*sync.Mutex, io.Writer) for thead-safe writing to net.Conn

---

paho/router.go

**ECA - Eclipse Contributer Agreement**
Ensure you have a valid, signed [ECA](https://www.eclipse.org/legal/ECA.php) for the email address associated with your Github account (or you sign off your PR with an ECA'd address)
Please provide enough information so that others can review your pull request: See issue #93 
Put `closes #93` in your comment to auto-close the issue that your PR fixes.

Fix StandardRouter topic matching for shared subscriptions

---

autopaho/auto.go

**Change**
As mentioned in #121, ``autophao.ClientConfig` provides no way to set `phao.Client.SetErrorLogger`. This change fixes it.
- Add `autopaho.ClientConfig.PhaoErrors` analogous to  `autopaho.ClientConfig.PhaoDebug`
- Set `phao.Client.SetErrorLogger` if `autopaho.Client Config.PahoErrors` is set.
**Testing**
`paho.Client` does not expose `errors`. So testing if it was correctly set is not possible.
closes #121

Add autopaho clientconfig pahoerrors

---

packets/connack.go

**Changing**
As mentioned in #120, fix protocol error code of CONNACK according to the spec. 
As bellow, protocol error code of DISCONNECT is 0x82,  CONNACK = 0x81 seems to be just typo.
https://github.com/eclipse/paho.golang/blob/d63b3b28d25ff73076c8846c92c4d062503e646e/packets/disconnect.go#L26
**Testing**
Test was passed by ```make test```
closes #120

Fix typo of protocol error code of CONNACK

---

paho/client.go

This patch is for fixing #101. As I commented in the GitHub issue, it can be easily reproduced and causes goroutine leak (memory leak). After the patch is applied, it cannot be reproduced by the reproduction code in the GitHub issue.
To prevent the issue c.expectConnack goroutine doesn't exit, caPacketCh and caPacketErr is changed to buffered channels from unbuffered one. comment are also added so that the buffers won't get deleted in future fixes.
closes #101

Fix the issue c.expectConnack goroutine doesn't exit #101

---

paho/client.go

I think it's better to replace hard-coded return code by constant, because there are already defined constants. It's a little confusing.
#132

Hard coded return codes of Auth packet are replaced by each defined constant

---

autopaho/cmd/rpc/config.go
autopaho/cmd/rpc/main.go
autopaho/examples/docker/subscriber/main.go
autopaho/extensions/rpc/rpc.go
packets/packets.go
packets/packets_test.go
packets/pingreq.go
packets/pingresp.go
packets/subscribe.go
paho/client.go
paho/client_test.go
paho/cmd/chat/main.go
paho/cmd/rpc/main.go
paho/cmd/stdoutsub/main.go
paho/cp_subscribe.go
paho/extensions/rpc/rpc.go
paho/message_ids.go

Enumerating a map isn't deterministic so we can't guarantee an order to the subscribe packet sent to the server, as the response only contains a slice of values we need to know what order the subscriptions were sent in so that the responses can be correlated, using a slice and putting the topic as a property of the suboptions allows us to be sure of this.
#123

Use slice for Subscriptions instead of map

---

paho/message_ids.go
paho/message_ids_test.go

This fix correspond to #135. 
Note that In this implemention, whether last MID is blank is also checked. (In current implemention of "master", checking  up to last MID - 1)
close #135

Fix not using max MID (full band of MID)

---

paho/server_test.go

Very small change, this makes the test logs easier to interpret.

Print control packet type string instead of number

---

packets/packets.go
packets/publish_test.go

Calling `ControlPacket.WriteTo` when `.Content` was a `Publish` resulted in incorrect flags. This PR resolves the issue and adds a test.
Closes #149

Correct handling of flags for PUBLISH packets in ControlPacket.WriteTo

---

paho/message_ids.go
paho/message_ids_test.go

This is related to #145 . 
To avoid panic, handling 0 Packet Identifier although it is invalid (valid range is 1 - 65535).

handling 0 Packet Identifier in MIDs

---

autopaho/auto.go
autopaho/error.go
autopaho/net.go

This enables handling connection errors based on response code received by the server.
Fixes #152

Add CONNACK packet to autopaho OnConnectError func

---

autopaho/auto.go
autopaho/error.go
autopaho/internal/testserver/testserver.go

autoPaho had the potential to call the error call beck multiple times in relation to one event.
This mirrored the `paho` functionality but does not make much sense from an end user perspective,
so this change prevents multiple calls to `OnClientError` in relation to a single connection.
We also prevent errors from being logger when the user has called `Disconnect` (it's not an error
if it's the result of a request) and add a test.
closes #157

Autopaho: Call error call back a maximum of once per connection

---

README.md
paho/session/state/ids_test.go
paho/session/state/sendquota.go
paho/session/state/sendquota_test.go
paho/session/state/state.go
paho/store/memory/store.go

This is required to avoid potential panic and improve logging.
Also tidied up some of the code that handles completion of the message lifecycle.
Ref issue #179

Reimplement receive-maximum quota handling

---

autopaho/auto.go
autopaho/auto_test.go
autopaho/cmd/rpc/config.go
autopaho/cmd/rpc/main.go
autopaho/error.go
autopaho/examples/basics/basics.go
autopaho/examples/docker/publisher/main.go
autopaho/examples/docker/readme.md
autopaho/examples/docker/subscriber/main.go
autopaho/examples/queue/main.go
autopaho/examples/queue/publish.go
autopaho/examples/queue/readme.md
autopaho/examples/queue/subscribe.go
autopaho/net.go
autopaho/persistence_test.go
autopaho/queue_test.go
autopaho/readme.md
internal/testserver/testserver.go

The autopaho config was a mix of public fields and private fields with setters. This change makes everything public in line with paho. The setters have been left for compatability.
Also remove the term "broker" because this is not used in the MQTT spec so is likely to be confusing.
Closes #174

consistent config structure in autopaho and rename "broker" to "server"

---

autopaho/auto_test.go
autopaho/cmd/rpc/config.go
autopaho/examples/basics/basics.go
autopaho/examples/docker/subscriber/main.go
autopaho/examples/queue/subscribe.go
autopaho/persistence_test.go
autopaho/queue_test.go
autopaho/readme.md
paho/client_test.go
paho/cmd/chat/main.go
paho/cmd/rpc/main.go
paho/cmd/stdoutsub/main.go
paho/router.go

SingleHandlerRouter did not adhere to the
requirements set out in the router interface
documentation.
Have retained NewSingleHandlerRouter so that
most code should run without modification.
ref #168

Remove SingleHandlerRouter

---

autopaho/auto.go
autopaho/examples/queue/publish.go
autopaho/queue/file/queue.go
autopaho/queue/file/queue_test.go
autopaho/queue/memory/queue.go
autopaho/queue/memory/queue_test.go
autopaho/queue/queue.go

If a queued message was corrupted on the disk then an infinite loop resulted (autopaho continually
attempted to send the same corrupt message). This change moves such messages out of the queue.
closes #193

Queued messages should be removed from the queue if they cannot be parsed

---

paho/session/state/sendquota.go
paho/session/state/sendquota_test.go

If the context was cancelled whilst `Acquire` was waiting, then the request remained in the
queue and would gain (and never release) the next slot. This would lead to a deadlock.

sendquota did not handle context cancellation correctly

---

autopaho/auto.go
autopaho/queue_test.go
internal/testserver/testserver.go
paho/session/state/state.go

This could lead to the client stalling with no messages going out.
ref #196

autopaho may stop publishing from queue if a publish times out

---

autopaho/auto.go
autopaho/queue/file/queue.go
autopaho/queue/file/queue_test.go
autopaho/queue/memory/queue.go
autopaho/queue/memory/queue_test.go
autopaho/queue/queue.go
autopaho/queue_test.go
internal/testserver/testserver.go
paho/session/state/state.go
paho/session/state/store.go
paho/store/file/store.go
paho/store/file/store_test.go
paho/store/memory/store.go

A corrupt file in the store should be ignored
(quarantined if possible) to avoid either
preventing the connection completing or an
infinite loop.
Also added test and modified queue for
consistency.
closes #195

Handle corrupt files in store

---

autopaho/auto.go

Previously if you wanted to subscribe and register a handler, then both a ConnectionManager and Router would be needed; this complicates passing the client around (or dependency injection).
ref #168

autopaho now provides `Router()`

---

autopaho/auto.go
autopaho/auto_test.go
autopaho/net.go

As per discussion in #192 I've added URL as a parameter, and also an example on how to use it to extract password from URL

pass `*url.URL` to ConnectPacketBuilder

---

CODE_OF_CONDUCT.md
SECURITY.md

Add paho project policy docs
Copied from https://www.eclipse.org/projects/tools/documentation.php?id=iot.paho
SECURITY.md modified to meet this projects needs.

Add paho project policy docs

---

autopaho/auto.go
autopaho/auto_test.go
internal/testserver/testserver.go

Reauthentication with MQTT5 Enhanced Authentication (AUTH packet exchange) in autopaho

---

autopaho/auto.go
paho/client.go
paho/client_test.go
paho/extensions/rpc/rpc.go
paho/packet_ids_test.go

Users could previously access/change the ClientConfig held by `paho.Client`; this invited race conditions (`paho.Client` could use values from the config at any time and no locking mechanism was provided).
To avoid this, the config is now private and examples etc have been updated. A getter for `ClientID` has been added (as this was needed in examples); I suspect additional getters may be of benefit (but will await feedback for that).
This may break some users code (but that is probably a good thing)
closes #210

paho `Client.ClientConfig` is now private

---

internal/basictestserver/server.go
paho/client.go
paho/client_test.go
paho/default_pinger_test.go
paho/packet_ids_test.go
paho/pinger.go
paho/pinger_test.go

New pinger implementation

---

autopaho/auto.go
autopaho/queue_test.go
paho/client.go

This is an initial solution to issue #214 (the autopaho queue would loop infinitely attempting to resend invalid messages). Further work is needed, but this deals with the main issue.
Ref #214

Provide a way to identify operations that should not be retried

---

autopaho/auto_test.go
autopaho/examples/docker/publisher/main.go
paho/client.go
paho/client_test.go
paho/default_pinger_test.go
paho/packet_ids_test.go
paho/pinger.go

* It was unclear what Client.mu protected.
* Using and using contexts to manage shutdown is easier to follow. 
* Reimplement Pinger using Context
Closes #227
Ref #148

Tidy up Mu, termination process and keep alive

---

autopaho/auto.go
paho/client.go

close https://github.com/eclipse/paho.golang/issues/233
close https://github.com/eclipse/paho.golang/issues/232

address issues with queue error handling in autopaho, return ErrInvalidArguments for invalid publish QoS in paho

---

paho/pinger.go

When running with a local server, there is a chance that `NewControlPacket(packets.PINGREQ).WriteTo(conn)` may return after the ping response has been handled. This led to invalid timeouts.
closes #237

Resolve erroneous ping timeout

---

packets/properties.go
packets/properties_test.go
paho/client.go
paho/cp_connect.go

**Do not create a Pull Request without creating an issue first**
#161 was created related to this request.
**The design of your solution to the problem should be discussed and agreed in an issue before submitting the PR**
According to [MQTTv5 spec](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901046), Maximum QoS property should not be included in CONNECT packet. Actually, when I tried to send CONNECT packet included that property to Mosquitto MQTT server, the connection was refused by Mosquitto. So, I think we should remove Maximum QoS property from CONNECT packet in this library.
note: This request is same with #240, but I remaked the request after some confirmations, because there was a problem with test on my envrionment (#242). As a result, the problem wasn't …

Remove MaximumQoS property from CONNECT packet #161

---

go.mod
go.sum

Update to Go version is in line with "Each major Go release is supported until there are two newer major releases". 
It's also needed due to the use of `context.AfterFunc`.
Closes #241

Update dependencies and set go.mod to `go 1.21`

---

autopaho/net.go

A ConnectTimeout setting must be respected while connecting through the proxy:
1. Call DialContext if the custom dialer implements it.
2. Perform the blocking Dial call in a new goroutine, and respect context cancellation (potentially "leaked" goroutine)

fix: respect context cancellation while using the provided Dialer

---

paho/client.go
paho/client_test.go

PublishWithOptions may return both nil error and nil PublishResponse when QoS0 is used, which can potentially result in nil pointer exceptions. This commit updates PublishWithOptions to return a pointer to an empty PublishResponse when QoS0 is used to eliminate this risk.
Closes #159

PublishWithOptions QoS0 return empty PublishRespoonse

---

paho/default_pinger_test.go
paho/pinger.go

In order to detect network issues in the application layer, PingHandler sends a PINGREQ, and if it doesn't receive a response within the specified KeepAlive period, the connection is closed. However, if the network is very slow and unstable, the WriteTo(conn) operation (which sends a PINGREQ) may block for quite some time, during which context cancellation and KeepAlive timeout are ignored. The call must be eventually unblocked due to TCP timeouts. (Note: I have an example where connection establishment through the proxy hung for 1 hour; it's already fixed with proxy.Dial and ContextDialer. However, I suspect the same could happen here as well)
Send a PINGREQ request in a separate goroutine. In case of KeepAlive timeout or context cancellation, the main goroutine does not wait until the …

Improve default ping handler

---

paho/client.go

Addresses [comment](https://github.com/eclipse/paho.golang/pull/255#issuecomment-2119397021).
This commit adds a comment explaining that the PublishResponse return value from Publish and PublishWithOptions should technically only be used for QOS1+. For QOS0, a default response with ReasonCode=0 (success) is returned.

Add Publish comment detailing PublishResponse usage

---

autopaho/auto.go
autopaho/auto_test.go
autopaho/backoff.go
autopaho/backoff_test.go
autopaho/examples/backoff/backoff.go
autopaho/examples/docker/publisher/main.go
autopaho/examples/docker/subscriber/main.go
autopaho/examples/rpc/main.go
autopaho/net.go
autopaho/persistence_test.go
autopaho/queue_test.go

This PR introduces the ability to use a dynamic backoff for reconnect attempts.
Its purpose is just to replace the current constant value with a more versatile option.
As default a backoff strategy is used which returns the same backoff value mimicking the previous behaviour.
In addition there is an exponential backoff available which will increase the max value on each attempt up to a configurable limit.
The created backoff is a random value between a configured non-zero minimum and the increasing max (up to the configured limit). Using a random value from an increasing range helps spread client reconnect attempts.
**Testing**
Existing code has been changed to use the same duration as before but now uses the constant backoff implementation instead. All tests pass.
Additionally there are …

Add option for dynamic backoff

---

paho/extensions/topicaliases/topicliases.go

Related: #271 and #276
This PR introduce `ResetAll` method in `TAHandler`. ResetAll should be called before reconnect. If not, topic alias is used after reconnect, and causes Protocol Error.
Here is a minimal sample code to use `TAHandler` with `autopaho`.
```go
maxTopicAlias := uint16(100)
ta := topicaliases.NewTAHandler(maxTopicAlias)
cliCfg := autopaho.ClientConfig{
ServerUrls:                    []*url.URL{u},
CleanStartOnInitialConnection: false,
OnConnectionUp: func(cm *autopaho.ConnectionManager, connAck *paho.Connack) {
ta.ResetAll()
},
ConnectPacketBuilder: func(c *paho.Connect, u *url.URL) (*paho.Connect, error) {
c.Properties = &paho.ConnectProperties{
TopicAliasMaximum: &maxTopicAlias,
}
return c, nil
},
ClientConfig: paho.ClientConfig{
PublishHook: ta.PublishHook,
},
}
```

Add ResetAll() in topicaliases to prevent error on reconnection

---

autopaho/auto_test.go
autopaho/queue_test.go
internal/basictestserver/server.go
paho/client.go
paho/default_pinger_test.go
paho/pinger.go

If a client regularly sends packets (e.g. publishes) then it's quite possible that a keepalive would never be sent. This may become an issue with a half open connection because TCP timeouts can take a long time to be detected. With this PR a keepalive will be sent if a packet has not been both sent AND received within the keepalive period. This will mean more network traffic for users who are just sending at QOS0 but should not have a significant impact on other users (and the improvement in reliability seems worth the cost).
Also improve reliability of tests.
Issue #288

Ping when no packets received within keep alive period

---

autopaho/queue/file/queue.go

Fix #308 to do the intended behaviour: create missing folders in autopaho file queue.
closes #308

fix folder existence check in autopaho file queue

---

paho/store/file/store.go

Logic bug meant an error was returned in the event `Stat` returned `os.IsNotExist`
If that happened the intent was to try to create the folder but that is not what was happening.

Filestore should attempt to create folder if it does not exist

---

paho/client_test.go
paho/cp_auth.go

The Success field is set to true even when the server denies your AUTH packet. Simply set this to false when a DISCONNECT response is received.
**Testing**
Added unit test that covers the scenario.
closes #314

Fix AuthResponse success value being set to true on error

---

packets/disconnect.go
paho/client_test.go

The issue would occur if the broker does not insert a zero for the properties length.
Please provide enough information so that others can review your pull request:
**Testing**
Tested against a mosquitto plugin that kicks clients. This sends the client a packet with the fixed header, a message len of 1, and a reason code, but no props length (allowed by MQTT v5 spec). Validated that with changes, OnServerDisconnect is called.
Added a test to replicate this scenario.
closes #302

Fix OnServerDisconnect not being called when packet has no properties
